__author__ = 'fitrah.wahyudi.imam@gmail.com'

LIST = {
    'AEG': "Aek Godang (AEG)",
    'ARD': "Alor (ARD)",
    'AMQ': "Ambon (AMQ)",
    'VPM': "Ampana (VPM)",
    'LMU': "Anambas (LMU)",
    'ABU': "Atambua (ABU)",
    'BPN': "Balikpapan (BPN)",
    'BJW': "Bajawa (BJW)",
    'BTJ': "Banda Aceh (BTJ)",
    'TKG': "Bandar Lampung (TKG)",
    'BDO': "Bandung (BDO)",
    'BDJ': "Banjarmasin (BDJ)",
    'BWX': "Banyuwangi (BWX)",
    'BTH': "Batam (BTH)",
    'BTW': "Batu Licin (BTW)",
    'BUW': "Baubau (BUW)",
    'BKS': "Bengkulu (BKS)",
    'BEJ': "Berau (BEJ)",
    'BMU': "Bima (BMU)",
    'WUB': "Buli (WUB)",
    'UOL': "Buol (UOL)",
    'CXP': "Cilacap (CXP)",
    'DPS': "Denpasar (DPS)",
    'DEX': "Dekai (DEX)",
    'DOB': "Dobo (DOB)",
    'DUM': "Dumai (DUM)",
    'ENE': "Ende (ENE)",
    'FKQ': "Fak Fak (FKQ)",
    'GLX': "Galela (GLX)",
    'GTO': "Gorontalo (GTO)",
    'GNS': "Gunung Sitoli (GNS)",
    'HLP': "Jakarta (HLP)",
    'CGK': "Jakarta (CGK)",
    'DJB': "Jambi (DJB)",
    'DJJ': "Jayapura (DJJ)",
    'JBB': "Jember (JBB)",
    'JOG': "Jogjakarta (JOG)",
    'KNG': "Kaimana (KNG)",
    'KDI': "Kendari (KDI)",
    'KRC': "Kerinci (KRC)",
    'KTG': "Ketapang (KTG)",
    'KBU': "Kotabaru (KBU)",
    'KOE': "Kupang (KOE)",
    'LBJ': "Labuan Bajo (LBJ)",
    'LAH': "Labuha (LAH)",
    'LKA': "Larantuka (LKA)",
    'LSW': "Lhokseumawe (LSW)",
    'LOP': "Lombok, Mataram (LOP)",
    'LKI': "Lubuk Linggau (LKI)",
    'LUW': "Luwuk (LUW)",
    'MLG': "Malang (MLG)",
    'MWW': "Malinau (MWW)",
    'MJU': "Mamuju (MJU)",
    'MDC': "Manado (MDC)",
    'MKW': "Manokwari (MKW)",
    'AMI': "Mataram (AMI)",
    'MOF': "Maumere (MOF)",
    'MES': "Medan (MES)",
    'KNO': "Medan Kuala Namu (KNO)",
    'MNA': "Melanguane (MNA)",
    'MKQ': "Merauke (MKQ)",
    'MEQ': "Meulaboh (MEQ)",
    'MKF': "Miangas (MKF)",
    'OTI': "Morotai (OTI)",
    'MWS': "Muara Bungo (MWS)",
    'MPC': "Mukomuko (MPC)",
    'NBX': "Nabire (NBX)",
    'NAM': "Namlea (NAM)",
    'NTX': "Natuna Ranai (NTX)",
    'PDG': "Padang (PDG)",
    'PXA': "Pagar Alam (PXA)",
    'PKY': "Palangkaraya (PKY)",
    'PLM': "Palembang (PLM)",
    'PLW': "Palu (PLW)",
    'LLO': "Palopo (LLO)",
    'PGK': "Pangkal Pinang (PGK)",
    'PKN': "Pangkalan Bun (PKN)",
    'PKU': "Pekanbaru (PKU)",
    'PUM': "Pomalaa (PUM)",
    'PNK': "Pontianak (PNK)",
    'PSJ': "Poso (PSJ)",
    'PSU': "Putus Sibau (PSU)",
    'RJM': "Raja Ampat (RJM)",
    'TXE': "Rembele-Takengon (TXE)",
    'RGT': "Rengat (RGT)",
    'RTI': "Rote (RTI)",
    'SBG': "Sabang (SBG)",
    'SMQ': "Sampit (SMQ)",
    'SQN': "Sanana (SQN)",
    'SRI': "Samarinda (SRI)",
    'SXK': "Saumlaki (SXK)",
    'SRG': "Semarang (SRG)",
    'YKR': "Selayar (YKR)",
    'FLZ': "Sibolga (FLZ)",
    'SMG': "Simeleu (SMG)",
    'DTB': "Silangit (DTB)",
    'SQG': "Sintang (SQG)",
    'SOC': "Solo (SOC)",
    'SOQ': "Sorong (SOQ)",
    'SWQ': "Sumbawa (SWQ)",
    'SUP': "Sumenep (SUP)",
    'SUB': "Surabaya (SUB)",
    'NAH': "Tahuna (NAH)",
    'TMC': "Tambolaka (TMC)",
    'TJQ': "Tanjung Pandan (TJQ)",
    'TNJ': "Tanjung Pinang (TNJ)",
    'TJS': "Tanjung Selor (TJS)",
    'TJG': "Tanjung Warukin (TJG)",
    'TRK': "Tarakan (TRK)",
    'TTE': "Ternate (TTE)",
    'TSY': "Tasikmalaya (TSY)",
    'TIM': "Timika (TIM)",
    'KAZ': "Tobelo (KAZ)",
    'TLI': "Toli-Toli (TLI)",
    'LUV': "Tual (LUV)",
    'UPG': "Ujung Pandang (UPG)",
    'WGP': "Waingapu (WGP)",
    'WMX': "Wamena (WMX)",
    'WNI': "Wakatobi (WNI)",
    'AOR': "Malaysia-Alor Setar (AOR)",
    'IPH': "Malaysia-Ipoh (IPH)",
    'JHB': "Malaysia-Johor Bahru (JHB)",
    'KTE': "Malaysia-Kerteh (KTE)",
    'KBR': "Malaysia-Kota Bahru (KBR)",
    'BKI': "Malaysia-Kota Kinabalu (BKI)",
    'KUL': "Malaysia-Kuala Lumpur KLIA (KUL)",
    'TGG': "Malaysia-Kuala Terengganu (TGG)",
    'KCH': "Malsyaia-Kuching (KCH)",
    'LGK': "Malaysia-Langkawi (LGK)",
    'MKZ': "Malaysia-Malacca (MKZ)",
    'MYY': "Malaysia-Miri (MYY)",
    'PEN': "Malaysia-Penang (PEN)",
    'SZB': "Malaysia-Subang (SZB)",
    'TWU': "Thailand-Tawau (TWU)",
    'DMK': "Thailand-Bangkok Donmueang (DMK)",
    'CNX': "Thailand-Chiang Mai (CNX)",
    'CEI': "Thailand-Chiang Rai (CEI)",
    'HDY': "Thailand-Hat Yai (HDY)",
    'KBV': "Thailand-Krabi (KBV)",
    'NST': "Thailand-Nakhon Si Thammarat (NST)",
    'HKT': "Thailand-Phuket (HKT)",
    'URT': "Thailand-Surat Thani (URT)",
    'UBP': "Thailand-Ubon Ratchathani (UBP)",
    'UTH': "Thailand-Udon Thani (UTH)",
    'HAN': "Vietnam-Hanoi (HAN)",
    'SGN': "VietNam-Ho Chi Minh City (SGN)",
    'PNH': "Khamboja-Phnom Penh (PNH)",
    'SIN': "Singapore (SIN)",
    'CMB': "Colombo (CMB)",
    'RNG': "Myanmar-Yangon (RNG)",
    'CGP': "Bangladesh-Chittagong (CGP)",
    'DAC': "Bangladesh-Dhaka (DAC)",
    'CSX': "China-Changsa (CSX)",
    'CTU': "China-Chengdu (CTU)",
    'CKG': "China-Chongqing (CKG)",
    'CAN': "China-Guangzhou (CAN)",
    'KWL': "China-Guilin (KWL)",
    'HFE': "China-Hafei (HFE)",
    'HAK': "China-Haikou (HAK)",
    'HGH': "China-Hangzhou (HGH)",
    'HKG': "China-Hong Kong (HKG)",
    'TNA': "China-Jinan (TNA)",
    'MFM': "China-Macau (MFM)",
    'KHN': "China-Nanchang (KHN)",
    'PVG': "China-Shanghai (PVG)",
    'SZX': "China-Shenzhen (SZX)",
    'TPE': "China-Taipei (TPE)",
    'WUH': "China-Wuhan (WUH)",
    'XIY': "China-Xi'an (XIY)",
    'AMD': "India-Ahmedabad (AMD)",
    'ATQ': "India-Amritsar (ATQ)",
    'MAA': "India-Chennai (MAA)",
    'DEL': "India-Delhi (DEL)",
    'COK': "India-Kochi (COK)",
    'BOM': "India-Mumbai (BOM)",
    'TRZ': "India-Tiruchirapally (TRZ)",
    'TRV': "India-Trivandrum (TRV)",
    'VTZ': "India-Visakhapatnam (VTZ)",
    'KTM': "Nepal-Kathmandu (KTM)",
    'LHE': "Pakistan-Lahore (LHE)",
    'BNE': "Australia-Brisbane (BNE)",
    'MEL': "Australia-Melbourne (MEL)",
    'PER': "Australia-Perth (PER)"
}
