var airports = [ "",
                "Aek Godang - AEG",
                "Alor - ARD",
                "Ambon - AMQ",
                "Ampana - VPM",
                "Anambas - LMU",
                "Atambua - ABU",
                "Balikpapan - BPN",
                "Bajawa - BJW",
                "Banda Aceh - BTJ",
                "Bandar Lampung - TKG",
                "Bandung - BDO",
                "Banjarmasin - BDJ",
                "Banyuwangi - BWX",
                "Batam - BTH",
                "Batu Licin - BTW",
                "Baubau - BUW",
                "Bengkulu - BKS",
                "Berau - BEJ",
                "Bima - BMU",
                "Buli - WUB",
                "Buol - UOL",
                "Cilacap - CXP",
                "Denpasar - DPS",
                "Dekai - DEX",
                "Dobo - DOB",
                "Dumai - DUM",
                "Ende - ENE",
                "Fak Fak - FKQ",
                "Galela - GLX",
                "Gorontalo - GTO",
                "Gunung Sitoli - GNS",
                "Jakarta Halim PK - HLP",
                "Jakarta - CGK",
                "Jambi - DJB",
                "Jayapura - DJJ",
                "Jember - JBB",
                "Jogjakarta - JOG",
                "Kaimana - KNG",
                "Kendari - KDI",
                "Kerinci - KRC",
                "Ketapang - KTG",
                "Kotabaru - KBU",
                "Kupang - KOE",
                "Labuan Bajo - LBJ",
                "Labuha - LAH",
                "Larantuka - LKA",
                "Lhokseumawe - LSW",
                "Lombok, Mataram - LOP",
                "Lubuk Linggau - LKI",
                "Luwuk - LUW",
                "Malang - MLG",
                "Malinau - MWW",
                "Mamuju - MJU",
                "Manado - MDC",
                "Manokwari - MKW",
                "Mataram - AMI",
                "Maumere - MOF",
                "Medan - MES",
                "Medan Kuala Namu - KNO",
                "Melanguane - MNA",
                "Merauke - MKQ",
                "Meulaboh - MEQ",
                "Miangas - MKF",
                "Morotai - OTI",
                "Muara Bungo - MWS",
                "Mukomuko - MPC",
                "Nabire - NBX",
                "Namlea - NAM",
                "Natuna Ranai - NTX",
                "Padang - PDG",
                "Pagar Alam - PXA",
                "Palangkaraya - PKY",
                "Palembang - PLM",
                "Palu - PLW",
                "Palopo - LLO",
                "Pangkal Pinang - PGK",
                "Pangkalan Bun - PKN",
                "Pekanbaru - PKU",
                "Pomalaa - PUM",
                "Pontianak - PNK",
                "Poso - PSJ",
                "Putus Sibau - PSU",
                "Raja Ampat - RJM",
                "Rembele-Takengon - TXE",
                "Rengat - RGT",
                "Rote - RTI",
                "Sabang - SBG",
                "Sampit - SMQ",
                "Sanana - SQN",
                "Samarinda - SRI",
                "Saumlaki - SXK",
                "Semarang - SRG",
                "Selayar - YKR",
                "Sibolga - FLZ",
                "Simeleu - SMG",
                "Silangit - DTB",
                "Sintang - SQG",
                "Solo - SOC",
                "Sorong - SOQ",
                "Sumbawa - SWQ",
                "Sumenep - SUP",
                "Surabaya - SUB",
                "Tahuna - NAH",
                "Tambolaka - TMC",
                "Tanjung Pandan - TJQ",
                "Tanjung Pinang - TNJ",
                "Tanjung Selor - TJS",
                "Tanjung Warukin - TJG",
                "Tarakan - TRK",
                "Ternate - TTE",
                "Tasikmalaya - TSY",
                "Timika - TIM",
                "Tobelo - KAZ",
                "Toli-Toli - TLI",
                "Tual - LUV",
                "Ujung Pandang - UPG",
                "Waingapu - WGP",
                "Wamena - WMX",
                "Wakatobi - WNI",
                "(MY) Alor Setar - AOR",
                "(MY) Ipoh - IPH",
                "(MY) Johor Bahru - JHB",
                "(MY) Kerteh - KTE",
                "(MY) Kota Bahru - KBR",
                "(MY) Kota Kinabalu - BKI",
                "(MY) Kuala Lumpur KLIA - KUL",
                "(MY) Kuala Terengganu - TGG",
                "(MY) Kuching - KCH",
                "(MY) Langkawi - LGK",
                "(MY) Malacca - MKZ",
                "(MY) Miri - MYY",
                "(MY) Penang - PEN",
                "(MY) Subang - SZB",
                "(MY) Tawau - TWU",
                "(TH) Bangkok Donmueang - DMK",
                "(TH) Chiang Mai - CNX",
                "(TH) Chiang Rai - CEI",
                "(TH) Hat Yai - HDY",
                "(TH) Krabi - KBV",
                "(TH) Nakhon Si Thammarat - NST",
                "(TH) Phuket - HKT",
                "(TH) Surat Thani - URT",
                "(TH) Ubon Ratchathani - UBP",
                "(TH) Udon Thani - UTH",
                "(VN) Hanoi - HAN",
                "(VN) Ho Chi Minh City - SGN",
                "(KH) Phnom Penh - PNH",
                "(SG) Singapore - SIN",
                "(LK) Colombo - CMB",
                "(MM) Yangon - RNG",
                "(BD) Chittagong - CGP",
                "(BD) Dhaka - DAC",
                "(CN) Changsa - CSX",
                "(CN) Chengdu - CTU",
                "(CN) Chongqing - CKG",
                "(CN) Guangzhou - CAN",
                "(CN) Guilin - KWL",
                "(CN) Hafei - HFE",
                "(CN) Haikou - HAK",
                "(CN) Hangzhou - HGH",
                "(CN) Hong Kong - HKG",
                "(CN) Jinan - TNA",
                "(CN) Macau - MFM",
                "(CN) Nanchang - KHN",
                "(CN) Shanghai - PVG",
                "(CN) Shenzhen - SZX",
                "(CN) Taipei - TPE",
                "(CN) Wuhan - WUH",
                "(CN) Xi'an - XIY",
                "(IN) Ahmedabad - AMD",
                "(IN) Amritsar - ATQ",
                "(IN) Chennai - MAA",
                "(IN) Delhi - DEL",
                "(IN) Kochi - COK",
                "(IN) Mumbai - BOM",
                "(IN) Tiruchirapally - TRZ",
                "(IN) Trivandrum - TRV",
                "(IN) Visakhapatnam - VTZ",
                "(NP) Kathmandu - KTM",
                "(PK) Lahore - LHE",
                "(AU) Brisbane - BNE",
                "(AU) Melbourne - MEL",
                "(AU) Perth - PER"
];

function get_list(mode){
    if (mode==null||mode==undefined){
        return airports;
    } else if(mode=='upper'){
        var new_list = [];
        for (var i=0; i < airports.length; i++){
            new_list.push(airports[i].toUpperCase());
        }
        return new_list;
    }
}

